package com.tl.spring_boot1.util;

import com.tl.spring_boot1.model.User;
import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.io.Decoders;
import io.jsonwebtoken.security.Keys;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import javax.crypto.SecretKey;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

@Component
public class JwtUtil {

    @Value("${jwt.secret.key}")
    private String secretKey;

    @Value("${jwt.expiration.seconds}")
    private Integer expirationSeconds;

    public String generateJwtToken(User user){
        // Building payload
        Map<String, Object> claims = new HashMap<>();
        claims.put("sub", user.getId().toString());
        claims.put("email",  user.getEmail());
        claims.put("role", user.getRole());

        // create issue and expiry time
        Date issuedAt = new Date();
        Date expirationDate = new Date(issuedAt.getTime() + expirationSeconds*1000L); // 1 hour expiry

        // Create jwt token and return
        return Jwts.builder()
                .claims(claims)
                .issuedAt(issuedAt)
                .expiration(expirationDate)
                .signWith(getSecretKey())
                .compact();

    }

    private SecretKey getSecretKey(){
        // The secret key passed here is a Base64 String representation of generated bytes.
        // converting this String back into bytes
        byte[] rawSecretKey = Decoders.BASE64.decode(secretKey);
        // convert these raw bytes into 'SecretKey' object
        return Keys.hmacShaKeyFor(rawSecretKey);
    }

    // this method will validate the token and return the payload of token as 'Claims' object if token is valid
    private Claims getClaimsFromToken(String token) {
        return Jwts.parser()
                .verifyWith(getSecretKey())
                .build()
                .parseSignedClaims(token)
                .getPayload();

        /* .parseSignedClaims(token) will throw error if token is not valid
            And if it is valid then 'getPayload()' will return payload of token which is represented as 'Claims' object
         */
    }

    public boolean validateToken(String token){
        try{
            getClaimsFromToken(token);
            return true;
        }catch(Exception e){
            return false;
        }
    }

    public Integer getIdFromToken(String token){
        Claims claims = getClaimsFromToken(token);
        return Integer.parseInt(claims.get("sub", String.class)); // claims.getSubject() can be used as well.
    }

    public String getEmailFromToken(String token){
        Claims claims = getClaimsFromToken(token);
        return claims.get("email", String.class);
    }

    public String getRoleFromToken(String token){
        Claims claims = getClaimsFromToken(token);
        return claims.get("role", String.class);
    }

    public Integer getExpirationTimeInSeconds(){
        return expirationSeconds;
    }
}
